åç§°ï¼š op_gl-usb150

åœ¨ï¼š
  å­˜å‚¨åº“è°ƒåº¦ï¼š
  å·¥ä½œæµè°ƒåº¦ï¼š
    è¾“å…¥ï¼š
      SSHï¼š
        æè¿°ï¼š'SSH è¿æ¥åˆ° Actions'
        è¦æ±‚ï¼šå‡
        é»˜è®¤å€¼ï¼š'å‡'

ç¯å¢ƒï¼š
  REPO_URLï¼šhttps://github.com/coolsnowwolf/lede
  REPO_BRANCHï¼šä¸»
  FEEDS_CONFï¼šfeeds.conf.default
  é…ç½®æ–‡ä»¶ï¼šgl-usb150.config
  DIY_P1_SHï¼šdiy-part1.sh
  DIY_P2_SHï¼šdiy-part2.sh
  UPLOAD_BIN_DIR:å‡
  ä¸Šä¼ å›ºä»¶ï¼šçœŸ
  UPLOAD_COWTRANSFERï¼šå‡
  ä¸Šä¼ _WETRANSFERï¼šå‡
  ä¸Šä¼ _å‘å¸ƒï¼šçœŸ
  TZï¼šäºšæ´²/ä¸Šæµ·

å·¥ä½œï¼š
  å»ºé€ ï¼š
    è¿è¡Œï¼š ubuntu-18.04

    è„šæ­¥ï¼š
    - åç§°ï¼šç»“å¸
      ç”¨é€”ï¼šactions/checkout@main

    - åç§°ï¼šåˆå§‹åŒ–ç¯å¢ƒ
      ç¯å¢ƒï¼š
        DEBIAN_FRONTENDï¼šéäº¤äº’å¼
      è¿è¡Œï¼š |
        é¡»è—¤ rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        é¡»è—¤ -E apt-get -qq æ›´æ–°
        é¡»è—¤ -E apt-get -qq å®‰è£… $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        é¡»è—¤ -E apt-get -qq æ¸…æ´
        é¡»è—¤ timedatectl è®¾ç½®æ—¶åŒºâ€œ$TZâ€
        é¡»è—¤ mkdir -p /workdir
        é¡»è—¤ chown $USER:$GROUPS /workdir
    - åç§°ï¼šå…‹éš†æºä»£ç 
      å·¥ä½œç›®å½•ï¼š/workdir
      è¿è¡Œï¼š |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    - åç§°ï¼šåŠ è½½è‡ªå®šä¹‰æè¦
      è¿è¡Œï¼š |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
    - åç§°ï¼šæ›´æ–°æè¦
      è¿è¡Œï¼š cd openwrt && ./scripts/feeds update -a

    - åç§°ï¼šå®‰è£…æè¦
      è¿è¡Œï¼š cd openwrt && ./scripts/feeds install -a

    - åç§°ï¼šåŠ è½½è‡ªå®šä¹‰é…ç½®
      è¿è¡Œï¼š |
        [ -e æ–‡ä»¶ ] && mv æ–‡ä»¶ openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
    - åç§°ï¼šSSH è¿æ¥åˆ° Actions
      ç”¨é€”ï¼šP3TERX/ssh2actions@v1.0.0
      å¦‚æœï¼š(github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || åŒ…å«ï¼ˆgithub.event.actionï¼Œ'ssh'ï¼‰
      ç¯å¢ƒï¼š
        TELEGRAM_CHAT_ID:${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKENï¼š${{secrets.TELEGRAM_BOT_TOKEN }}

    - åç§°ï¼šä¸‹è½½åŒ…
      ç¼–å·ï¼šåŒ…è£¹
      è¿è¡Œï¼š |
        cd openwrt
        è¿›è¡Œå®šä¹‰
        è¿›è¡Œä¸‹è½½ -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - åç§°ï¼šç¼–è¯‘å›ºä»¶
      idï¼šç¼–è¯‘
      è¿è¡Œï¼š |
        cd openwrt
        echo -e "$(nproc) çº¿ç¨‹ç¼–è¯‘"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    - åç§°ï¼šæ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      å¦‚æœï¼šï¼ˆï¼å–æ¶ˆï¼ˆï¼‰ï¼‰
      è¿è¡Œï¼šdf -hT

    - åç§°ï¼šä¸Šä¼ binç›®å½•
      ç”¨é€”ï¼šactions/upload-artifact@main
      å¦‚æœï¼šsteps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      å’Œï¼š
        åç§°ï¼šOpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        è·¯å¾„ï¼šopenwrt/bin

    - åç§°ï¼šæ•´ç†æ–‡ä»¶
      idï¼šç»„ç»‡
      å¦‚æœï¼šenv.UPLOAD_FIRMWARE == 'true' && !cancelled()
      è¿è¡Œï¼š |
        cd openwrt/bin/targets/*/*
        rm -rf åŒ…
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - åç§°ï¼šä¸Šä¼ å›ºä»¶ç›®å½•
      ç”¨é€”ï¼šactions/upload-artifact@main
      å¦‚æœï¼šsteps.organize.outputs.status == 'success' && !cancelled()
      å’Œï¼š
        åç§°ï¼šOpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        è·¯å¾„ï¼š${{ env.FIRMWARE }}

    - åç§°ï¼šä¸Šä¼ å›ºä»¶åˆ°cowtransfer
      idï¼šcowtransfer
      å¦‚æœï¼šsteps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      è¿è¡Œï¼š |
        curl -fsSL git.io/file-transfer | å˜˜
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
    - åç§°ï¼šä¸Šä¼ å›ºä»¶åˆ° WeTransfer
      idï¼šwetransfer
      å¦‚æœï¼šsteps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
      è¿è¡Œï¼š |
        curl -fsSL git.io/file-transfer | å˜˜
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
    - åç§°ï¼šç”Ÿæˆå‘å¸ƒæ ‡ç­¾
      ç¼–å·ï¼šæ ‡ç­¾
      å¦‚æœï¼šenv.UPLOAD_RELEASE == 'true' && !cancelled()
      è¿è¡Œï¼š |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        è§¦æ‘¸é‡Šæ”¾.txt
        [ $UPLOAD_COWTRANSFER = true ] && echo "ğŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
        [ $UPLOAD_WETRANSFER = true ] && echo "ğŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
        echo "::set-output name=status::success"
    - åç§°ï¼šä¸Šä¼ å›ºä»¶å‘å¸ƒ
      ç”¨é€”ï¼šsoftprops/action-gh-release@v1
      å¦‚æœï¼šsteps.tag.outputs.status == 'success' && !cancelled()
      ç¯å¢ƒï¼š
        GITHUB_TOKENï¼š${{secrets.GITHUB_TOKEN }}
      å’Œï¼š
        æ ‡ç­¾åç§°ï¼š${{ steps.tag.outputs.release_tag }}
        body_pathï¼šrelease.txt
        æ–‡ä»¶ï¼š${{ env.FIRMWARE }}/*

    - åç§°ï¼šåˆ é™¤å·¥ä½œæµè¿è¡Œ
      ç”¨é€”ï¼šGitRML/delete-workflow-runs@main
      å’Œï¼š
        ä¿ç•™å¤©æ•°ï¼š1
        keep_minimum_runs:3

    - åç§°ï¼šåˆ é™¤æ—§ç‰ˆæœ¬
      ç”¨é€”ï¼šdev-drprasad/delete-older-releases@v0.1.0
      å¦‚æœï¼šenv.UPLOAD_RELEASE == 'true' && !cancelled()
      å’Œï¼š
        ä¿æŒæœ€æ–°ï¼š9
        delete_tags:çœŸ
      ç¯å¢ƒï¼š
        GITHUB_TOKENï¼š${{secrets.GITHUB_TOKEN }}
